FROM led_mon-base-img

ENV HOME=/home/webserver
ENV LED_MON_EXEC=/usr/local/bin/led_mon
ENV LED_MON_LIB=/usr/local/lib
ENV LD_LIBRARY_PATH=${LED_MON_LIB}
ENV LED_MON_HOME=${HOME}/led_mon
ENV LED_MON_SETTINGS_JSON=${LED_MON_HOME}/led_mon_settings.json

#ENV HTTP_SERVER_IP=192.168.1.243
#ENV HTTP_SERVER_PORT=8081
#ENV uSECONDS=250000
#ENV PER_CPU=true


ENV HTTP_SERVER_IP=192.168.1.243
ENV HTTP_SERVER_PORT=8081
ENV uSECONDS=250000
ENV PER_CPU=false

RUN useradd -ms /bin/bash webserver
WORKDIR /home/webserver/

RUN git clone -b test https://github.com/calvindo95/led_mon.git && \
    cd led_mon/include && wget https://github.com/nlohmann/json/releases/download/v3.11.2/json.hpp && cd .. && \
    mkdir build && cd build && \
    cmake .. && \
    cmake --build . -j4 --target install

COPY --chown=webserver:webserver led_mon_settings.json $LED_MON_SETTINGS_JSON

#USER webserver
WORKDIR /home/webserver/
CMD ["/home/webserver/led_mon/scripts/run_server.sh"]